### ISSUE TITLE
Feat: Add support for `o1`, `o1-preview`, and `o1-mini` on the OpenAI provider.

### ISSUE THREAD

**Issue by Christopher-Hayes** [vscode-reborn-ai/vscode-reborn-ai#130]
## Description:
- **Objective:** Implement support for three new OpenAI models in the VSCode Reborn AI extension.
- **Models to be Added:**
  - `o1`
  - `o1-preview`
  - `o1-mini`

## Purpose:
- Enhance the functionality of the extension by integrating these specific OpenAI models.
- **Side quest:** It would be nice if we showed the status of the reasoning in the same way ChatGPT does.

## Docs

https://platform.openai.com/docs/guides/reasoning

**Comment by Christopher-Hayes** [comment]
These models are already available through OpenRouter.ai. I personally am not a Tier 5 OpenAI API user, so my testing with the OpenAI provider is limited. It should be straight-forward to add the model IDs, but the more fancy feature of showing the "thoughts" of `o1` might have to wait until OpenAI makes it available to lower tier API users.

**Comment by PeterDaveHello** [comment]
@Christopher-Hayes please send me an email or DM me on X, I can help with that.

**Comment by Christopher-Hayes** [comment]
@PeterDaveHello Awesome. One problem - I couldn't find your email, and X doesn't let me DM without paying. But, I do have a public GitHub email, you can email me at `chris+git@hayes.software`.

**Comment by Christopher-Hayes** [comment]
Oops, I see it now. I'm so used to everyone having private GitHub emails, I forgot to look there.
