### ISSUE TITLE
Only show notifications if ChatGPT pane is out of focus

### ISSUE THREAD

**Issue by moritztim** [vscode-reborn-ai/vscode-reborn-ai#59]
### Describe the feature

I think the notification feature would be nice to have but it gets in the way when I'm already focused on the chatgpt window. I propose an additional Setting to `Show Notifications while in Focus`

**Comment by Christopher-Hayes** [comment]
@moritz-t-w could you clarify what kind of notifications these are?

Are you referring to the notification where an AI response seems incomplete? I think we might just get rid of the notification for that. Notifications were added a long time ago before this project was forked, and with the UI a lot more advanced now, I think I may just replace that with a small button below any messages that appear to be incomplete.

**Comment by moritz-t-w** [comment]
There is a setting for notifications when the answer is complete, search in the extension settings for it, I can't remember the name rn. It sends you a notification every time you get a response, even if you're actively using the chatgpt pane

**Comment by Christopher-Hayes** [comment]
Ah, I didn't know this was even an option. We have a ton of settings, so I'll probably just suppress the notification when in focus.
