### ISSUE TITLE
Bug: When asking for markdown it does not show the actual markdown

### ISSUE THREAD

**Issue by Christopher-Hayes** [vscode-reborn-ai/vscode-reborn-ai#6]
## Related

[When asking for markdown it does not show the actual markdown](https://github.com/gencay/vscode-chatgpt/issues/164)

**Comment by frankie-zeng** [comment]
+1

**Comment by Christopher-Hayes** [comment]
**Note that** - Sometimes when you ask for markdown, ChatGPT might respond by showing a code block with the markdown in it, and other times it might just render the markdown directly in the conversation.

To fix the issue where markdown is rendered but the code is not shown, enable <kbd>More Actions</kbd> > <kbd>View</kbd> > <kbd>Show Markdown</kbd>. This will turn off markdown rendering.
