### ISSUE TITLE
Price Preview

### ISSUE THREAD

**Issue by moritztim** [vscode-reborn-ai/vscode-reborn-ai#60]
### Describe the feature

Instead of having to click on the tokens, it'd be nice to see the max. cost right below the input field like this:
![mockup a (no ≤)](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/90388353/9fc3d809-d50d-4aae-8545-1caed7315487)
or like this:
![mockup b (with ≤)](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/90388353/5f347e88-2188-4ff8-bfc9-b92bcda7a235)

**Comment by Christopher-Hayes** [comment]
thanks @moritz-t-w, yeah just showing the cost would be more helpful than the number of tokens
