### ISSUE TITLE
Make TokenCountPopup more readable

### ISSUE THREAD

**Issue by moritztim** [vscode-reborn-ai/vscode-reborn-ai#61]
### Describe the feature

![current](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/90388353/5943c6b8-34af-402d-9fc1-c00524e738f0)

I think the token count popup is a bit cluttered.
I've made some Mockups, with incremental changes:
Shorten token to price calculation and move info on how it's calculated into an info popup (which would show up when you hover over the info symbol)
![Mockup 1](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/90388353/b6135490-d628-404a-bc41-55f702129870)
Improve calculation wording
![Mockup 2](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/90388353/c15b431f-e1ff-482e-a9b6-d4e9f894f282)
Shorten the tip at the bottom
![Mockup 3](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/90388353/05152aec-afb9-471b-9a25-35379f604fd3)

Maybe you could even make a table with the lowest and highest price.

**Comment by Christopher-Hayes** [comment]
Thank you for the suggestions @moritz-t-w
