### ISSUE TITLE
Let's use AI to help review pull requests?

### ISSUE THREAD

**Issue by PeterDaveHello** [vscode-reborn-ai/vscode-reborn-ai#90]
It'll be great to use AI to help review pull requests, not to replace the reviewer, but just like this tool itself, to help enhance the efficiency and also help catch something that might be missing.

I'm not CodeRabbit relative, but I did try it out with some other projects. It looks fine for Open Source projects: https://coderabbit.ai/, and there are also some other choices like:

- https://github.com/freeedcom/ai-codereviewer
- https://github.com/sourcegraph/cody
- https://github.com/sourcery-ai/sourcery

Maybe we can use one or some of them to speed up the development here ⚡

**Comment by Christopher-Hayes** [comment]
Good idea, @coderabbitai added.
