### ISSUE TITLE
Add a EditorConfig config file to prevent touching irrelated formatting

### ISSUE THREAD

**Issue by PeterDaveHello** [vscode-reborn-ai/vscode-reborn-ai#96]
There are some final newline character changes in at least `package.json` and `package.nls.*.json`. Maybe we should use [EditorConfig](https://editorconfig.org/) to help maintain consistent styles and minimize the diffs from different contributions. This will help minimize the code review and tracing load. Also, it's kind of best practice.

What do you think @Christopher-Hayes

**Comment by Christopher-Hayes** [comment]
Sure, sounds good to me if you want to set that up. We do already have ESLint for JS/TS stuff, so ideally this wouldn't conflict with the ESLint rules we already have set.

**Comment by PeterDaveHello** [comment]
Great, PR sent.
